// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuanLyHocBong_UNETI2_TI17A3HN.Data;

#nullable disable

namespace QuanLyHocBong_UNETI2_TI17A3HN.Migrations
{
    [DbContext(typeof(QuanLyHocBong_UNETI2_TI17A3HNContext))]
    [Migration("20261004143129_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QuanLyHocBong_UNETI2_TI17A3HN.Models.DonViTaiTro", b =>
                {
                    b.Property<int>("MaDonViTaiTro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDonViTaiTro"));

                    b.Property<string>("EmailLienHe")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("TenDonViTaiTro")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("MaDonViTaiTro");

                    b.HasIndex("TenDonViTaiTro")
                        .IsUnique();

                    b.ToTable("DonViTaiTro");

                    b.HasData(
                        new
                        {
                            MaDonViTaiTro = 1,
                            EmailLienHe = "contact@vingroup.com",
                            MoTa = "Tập đoàn Vingroup tài trợ cho sinh viên xuất sắc",
                            TenDonViTaiTro = "Quỹ Khuyến học Vingroup",
                            TrangThai = true
                        });
                });

            modelBuilder.Entity("QuanLyHocBong_UNETI2_TI17A3HN.Models.HoSoHocBong", b =>
                {
                    b.Property<int>("MaHoSoHocBong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaHoSoHocBong"));

                    b.Property<string>("GhiChu")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("MaHocBong")
                        .HasColumnType("int");

                    b.Property<int>("MaSinhVien")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayNop")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayXuLy")
                        .HasColumnType("datetime2");

                    b.Property<string>("NhanXetXetDuyet")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ThuXinHocBong")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaHoSoHocBong");

                    b.HasIndex("MaHocBong");

                    b.HasIndex("MaSinhVien");

                    b.ToTable("HoSoHocBong");

                    b.HasData(
                        new
                        {
                            MaHoSoHocBong = 1,
                            GhiChu = "Đã nộp kèm chứng nhận ngoại khóa",
                            MaHocBong = 1,
                            MaSinhVien = 1,
                            NgayNop = new DateTime(2026, 9, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ThuXinHocBong = "Em mong muốn nhận học bổng để phát triển chuyên môn Backend.",
                            TrangThai = "Chờ duyệt"
                        });
                });

            modelBuilder.Entity("QuanLyHocBong_UNETI2_TI17A3HN.Models.HocBong", b =>
                {
                    b.Property<int>("MaHocBong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaHocBong"));

                    b.Property<string>("BacDaoTao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("DiemTrungBinhToiThieu")
                        .HasColumnType("decimal(4,2)");

                    b.Property<string>("DieuKienXetHocBong")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("HanNopHoSo")
                        .HasColumnType("datetime2");

                    b.Property<int>("MaDonViTaiTro")
                        .HasColumnType("int");

                    b.Property<string>("MoTaHocBong")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("NgayBatDauNhanHoSo")
                        .HasColumnType("datetime2");

                    b.Property<int>("SoSuat")
                        .HasColumnType("int");

                    b.Property<string>("TenHocBong")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaHocBong");

                    b.HasIndex("MaDonViTaiTro");

                    b.ToTable("HocBong");

                    b.HasData(
                        new
                        {
                            MaHocBong = 1,
                            BacDaoTao = "Đại học",
                            DiemTrungBinhToiThieu = 3.6m,
                            DieuKienXetHocBong = "Không nợ môn, ĐTB >= 3.6",
                            HanNopHoSo = new DateTime(2026, 11, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MaDonViTaiTro = 1,
                            MoTaHocBong = "Dành cho sinh viên xuất sắc khối ngành CNTT",
                            NgayBatDauNhanHoSo = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SoSuat = 10,
                            TenHocBong = "Học bổng Vingroup Xuất sắc 2026",
                            TrangThai = "Đang nhận hồ sơ"
                        });
                });

            modelBuilder.Entity("QuanLyHocBong_UNETI2_TI17A3HN.Models.KetQuaHocBong", b =>
                {
                    b.Property<int>("MaKetQuaHocBong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaKetQuaHocBong"));

                    b.Property<decimal?>("DiemDanhGia")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("KetQua")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("MaHoSoHocBong")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<string>("NhanXet")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("MaKetQuaHocBong");

                    b.HasIndex("MaHoSoHocBong")
                        .IsUnique();

                    b.ToTable("KetQuaHocBong");

                    b.HasData(
                        new
                        {
                            MaKetQuaHocBong = 1,
                            DiemDanhGia = 95.5m,
                            KetQua = "Được cấp học bổng",
                            MaHoSoHocBong = 1,
                            NgayCapNhat = new DateTime(2026, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NhanXet = "Sinh viên xuất sắc, thái độ phỏng vấn tốt"
                        });
                });

            modelBuilder.Entity("QuanLyHocBong_UNETI2_TI17A3HN.Models.LichPhongVan", b =>
                {
                    b.Property<int>("MaLichPhongVan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLichPhongVan"));

                    b.Property<string>("DiaDiemHoacLienKet")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("GhiChu")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("HinhThucPhongVan")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("MaHoSoHocBong")
                        .HasColumnType("int");

                    b.Property<string>("NguoiPhongVan")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("ThoiGianBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ThoiGianKetThuc")
                        .HasColumnType("datetime2");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaLichPhongVan");

                    b.HasIndex("MaHoSoHocBong");

                    b.ToTable("LichPhongVan");

                    b.HasData(
                        new
                        {
                            MaLichPhongVan = 1,
                            DiaDiemHoacLienKet = "Phòng họp 1 - Cơ sở Lĩnh Nam",
                            GhiChu = "Sinh viên mang theo thẻ sinh viên và CMND",
                            HinhThucPhongVan = "Trực tiếp",
                            MaHoSoHocBong = 1,
                            NguoiPhongVan = "Hội đồng xét duyệt",
                            ThoiGianBatDau = new DateTime(2026, 10, 10, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            ThoiGianKetThuc = new DateTime(2026, 10, 10, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            TrangThai = "Đã lên lịch"
                        });
                });

            modelBuilder.Entity("QuanLyHocBong_UNETI2_TI17A3HN.Models.SinhVien", b =>
                {
                    b.Property<int>("MaSinhVien")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaSinhVien"));

                    b.Property<string>("BacDaoTao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("DiemTrungBinhTichLuy")
                        .HasColumnType("decimal(4,2)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("GioiTinh")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("MaTaiKhoan")
                        .HasColumnType("int");

                    b.Property<string>("Nganh")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("ThanhTichHocTap")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaSinhVien");

                    b.HasIndex("MaTaiKhoan")
                        .IsUnique();

                    b.ToTable("SinhVien");

                    b.HasData(
                        new
                        {
                            MaSinhVien = 1,
                            BacDaoTao = "Đại học",
                            DiaChi = "Hà Nội",
                            DiemTrungBinhTichLuy = 3.8m,
                            Email = "sv001@uneti.edu.vn",
                            GioiTinh = "Nam",
                            HoTen = "Trần Sinh Viên",
                            MaTaiKhoan = 3,
                            Nganh = "Hệ thống thông tin",
                            NgaySinh = new DateTime(2004, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SoDienThoai = "0912345678",
                            ThanhTichHocTap = "Giải Nhất Olympic Tin học",
                            TrangThai = "Đang học"
                        });
                });

            modelBuilder.Entity("QuanLyHocBong_UNETI2_TI17A3HN.Models.TaiKhoan", b =>
                {
                    b.Property<int>("MaTaiKhoan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaTaiKhoan"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.Property<string>("VaiTro")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("MaTaiKhoan");

                    b.HasIndex("TenDangNhap")
                        .IsUnique();

                    b.ToTable("TaiKhoan");

                    b.HasData(
                        new
                        {
                            MaTaiKhoan = 1,
                            Email = "admin@uneti.edu.vn",
                            HoTen = "Quản trị viên",
                            MatKhau = "123456",
                            TenDangNhap = "admin",
                            TrangThai = true,
                            VaiTro = "Admin"
                        },
                        new
                        {
                            MaTaiKhoan = 2,
                            Email = "canboa@uneti.edu.vn",
                            HoTen = "Cán bộ Nguyễn Văn A",
                            MatKhau = "123456",
                            TenDangNhap = "canbo",
                            TrangThai = true,
                            VaiTro = "Cán bộ học bổng"
                        },
                        new
                        {
                            MaTaiKhoan = 3,
                            Email = "sv001@uneti.edu.vn",
                            HoTen = "Trần Sinh Viên",
                            MatKhau = "123456",
                            TenDangNhap = "sv001",
                            TrangThai = true,
                            VaiTro = "Sinh viên"
                        });
                });

            modelBuilder.Entity("QuanLyHocBong_UNETI2_TI17A3HN.Models.HoSoHocBong", b =>
                {
                    b.HasOne("QuanLyHocBong_UNETI2_TI17A3HN.Models.HocBong", "HocBong")
                        .WithMany("HoSoHocBongs")
                        .HasForeignKey("MaHocBong")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QuanLyHocBong_UNETI2_TI17A3HN.Models.SinhVien", "SinhVien")
                        .WithMany("HoSoHocBongs")
                        .HasForeignKey("MaSinhVien")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("HocBong");

                    b.Navigation("SinhVien");
                });

            modelBuilder.Entity("QuanLyHocBong_UNETI2_TI17A3HN.Models.HocBong", b =>
                {
                    b.HasOne("QuanLyHocBong_UNETI2_TI17A3HN.Models.DonViTaiTro", "DonViTaiTro")
                        .WithMany("HocBongs")
                        .HasForeignKey("MaDonViTaiTro")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DonViTaiTro");
                });

            modelBuilder.Entity("QuanLyHocBong_UNETI2_TI17A3HN.Models.KetQuaHocBong", b =>
                {
                    b.HasOne("QuanLyHocBong_UNETI2_TI17A3HN.Models.HoSoHocBong", "HoSoHocBong")
                        .WithOne("KetQuaHocBong")
                        .HasForeignKey("QuanLyHocBong_UNETI2_TI17A3HN.Models.KetQuaHocBong", "MaHoSoHocBong")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HoSoHocBong");
                });

            modelBuilder.Entity("QuanLyHocBong_UNETI2_TI17A3HN.Models.LichPhongVan", b =>
                {
                    b.HasOne("QuanLyHocBong_UNETI2_TI17A3HN.Models.HoSoHocBong", "HoSoHocBong")
                        .WithMany("LichPhongVans")
                        .HasForeignKey("MaHoSoHocBong")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HoSoHocBong");
                });

            modelBuilder.Entity("QuanLyHocBong_UNETI2_TI17A3HN.Models.SinhVien", b =>
                {
                    b.HasOne("QuanLyHocBong_UNETI2_TI17A3HN.Models.TaiKhoan", "TaiKhoan")
                        .WithOne("SinhVien")
                        .HasForeignKey("QuanLyHocBong_UNETI2_TI17A3HN.Models.SinhVien", "MaTaiKhoan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("QuanLyHocBong_UNETI2_TI17A3HN.Models.DonViTaiTro", b =>
                {
                    b.Navigation("HocBongs");
                });

            modelBuilder.Entity("QuanLyHocBong_UNETI2_TI17A3HN.Models.HoSoHocBong", b =>
                {
                    b.Navigation("KetQuaHocBong")
                        .IsRequired();

                    b.Navigation("LichPhongVans");
                });

            modelBuilder.Entity("QuanLyHocBong_UNETI2_TI17A3HN.Models.HocBong", b =>
                {
                    b.Navigation("HoSoHocBongs");
                });

            modelBuilder.Entity("QuanLyHocBong_UNETI2_TI17A3HN.Models.SinhVien", b =>
                {
                    b.Navigation("HoSoHocBongs");
                });

            modelBuilder.Entity("QuanLyHocBong_UNETI2_TI17A3HN.Models.TaiKhoan", b =>
                {
                    b.Navigation("SinhVien")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
